format_version: 3
pipelines:
  yardsale:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/troyhart/yardsale.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build-and-unit-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          compile-source:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: ./mvnw
                run_if: passed
